"""create all tables

Revision ID: 9a59b8d94c73
Revises: 
Create Date: 2026-04-15 16:25:44.614322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a59b8d94c73'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('md_factory',
    sa.Column('factory_id', sa.String(length=36), nullable=False),
    sa.Column('factory_code', sa.String(length=50), nullable=False),
    sa.Column('factory_name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('factory_id'),
    sa.UniqueConstraint('factory_code')
    )
    op.create_table('md_material',
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('material_code', sa.String(length=50), nullable=False),
    sa.Column('material_name', sa.String(length=200), nullable=False),
    sa.Column('material_type', sa.String(length=30), nullable=False),
    sa.Column('smt_placement_points', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('unit_volume', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('unit_weight', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('material_id'),
    sa.UniqueConstraint('material_code')
    )
    op.create_table('md_ng_type',
    sa.Column('ng_code', sa.String(length=20), nullable=False),
    sa.Column('ng_name', sa.String(length=100), nullable=False),
    sa.Column('impact_level', sa.String(length=10), nullable=False),
    sa.Column('repairable', sa.String(length=20), nullable=False),
    sa.Column('repair_time_sec', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('repair_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ng_code')
    )
    op.create_table('md_product',
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('product_category', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('standard_changeover_time', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('product_code')
    )
    op.create_table('md_stage',
    sa.Column('stage_id', sa.String(length=36), nullable=False),
    sa.Column('factory_id', sa.String(length=36), nullable=False),
    sa.Column('stage_code', sa.String(length=50), nullable=False),
    sa.Column('stage_name', sa.String(length=200), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('stage_type', sa.String(length=50), nullable=False),
    sa.Column('line_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('creator_binding_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['md_factory.factory_id'], ),
    sa.PrimaryKeyConstraint('stage_id'),
    sa.UniqueConstraint('factory_id', 'stage_code')
    )
    op.create_table('md_warehouse',
    sa.Column('warehouse_id', sa.String(length=36), nullable=False),
    sa.Column('factory_id', sa.String(length=36), nullable=False),
    sa.Column('warehouse_code', sa.String(length=50), nullable=False),
    sa.Column('warehouse_name', sa.String(length=200), nullable=False),
    sa.Column('warehouse_type', sa.String(length=30), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('total_capacity', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('creator_binding_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['md_factory.factory_id'], ),
    sa.PrimaryKeyConstraint('warehouse_id')
    )
    op.create_table('md_work_calendar',
    sa.Column('calendar_id', sa.String(length=36), nullable=False),
    sa.Column('factory_id', sa.String(length=36), nullable=False),
    sa.Column('calendar_date', sa.Date(), nullable=False),
    sa.Column('is_working_day', sa.Boolean(), nullable=False),
    sa.Column('day_type', sa.String(length=20), nullable=False),
    sa.Column('total_work_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('remarks', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['md_factory.factory_id'], ),
    sa.PrimaryKeyConstraint('calendar_id')
    )
    op.create_table('md_worker_type',
    sa.Column('worker_type_id', sa.String(length=36), nullable=False),
    sa.Column('factory_id', sa.String(length=36), nullable=False),
    sa.Column('worker_type_code', sa.String(length=50), nullable=False),
    sa.Column('worker_type_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['md_factory.factory_id'], ),
    sa.PrimaryKeyConstraint('worker_type_id')
    )
    op.create_table('tpl_parameter_template',
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('template_name', sa.String(length=200), nullable=False),
    sa.Column('template_type', sa.String(length=30), nullable=False),
    sa.Column('template_description', sa.Text(), nullable=True),
    sa.Column('factory_id', sa.String(length=36), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('template_content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['md_factory.factory_id'], ),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_table('md_production_line',
    sa.Column('line_id', sa.String(length=36), nullable=False),
    sa.Column('stage_id', sa.String(length=36), nullable=False),
    sa.Column('line_code', sa.String(length=50), nullable=False),
    sa.Column('line_name', sa.String(length=200), nullable=False),
    sa.Column('smt_pph', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('operation_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('creator_binding_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['md_stage.stage_id'], ),
    sa.PrimaryKeyConstraint('line_id'),
    sa.UniqueConstraint('stage_id', 'line_code')
    )
    op.create_table('md_shift',
    sa.Column('shift_id', sa.String(length=36), nullable=False),
    sa.Column('calendar_id', sa.String(length=36), nullable=False),
    sa.Column('shift_name', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('work_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('break_minutes', sa.Integer(), nullable=True),
    sa.Column('shift_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['md_work_calendar.calendar_id'], ),
    sa.PrimaryKeyConstraint('shift_id')
    )
    op.create_table('sim_simulation_plan',
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('plan_name', sa.String(length=200), nullable=False),
    sa.Column('plan_description', sa.Text(), nullable=True),
    sa.Column('factory_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('enabled_simulators', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('simulation_duration_hours', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('base_data_version', sa.String(length=50), nullable=True),
    sa.Column('parameter_template_id', sa.String(length=36), nullable=True),
    sa.Column('input_template_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['md_factory.factory_id'], ),
    sa.ForeignKeyConstraint(['parameter_template_id'], ['tpl_parameter_template.template_id'], ),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_table('biz_demand_forecast',
    sa.Column('forecast_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=True),
    sa.Column('time_granularity', sa.String(length=10), nullable=False),
    sa.Column('period_label', sa.String(length=20), nullable=False),
    sa.Column('period_start_date', sa.Date(), nullable=False),
    sa.Column('period_end_date', sa.Date(), nullable=False),
    sa.Column('demand_quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('data_source', sa.String(length=30), nullable=False),
    sa.Column('source_system', sa.String(length=50), nullable=True),
    sa.Column('sync_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['sim_simulation_plan.plan_id'], ),
    sa.PrimaryKeyConstraint('forecast_id')
    )
    op.create_table('biz_inventory_snapshot',
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('warehouse_id', sa.String(length=36), nullable=False),
    sa.Column('material_code', sa.String(length=50), nullable=False),
    sa.Column('total_quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('available_quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(), nullable=False),
    sa.Column('data_source', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['sim_simulation_plan.plan_id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['md_warehouse.warehouse_id'], ),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_table('biz_material_supply',
    sa.Column('supply_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('material_code', sa.String(length=50), nullable=False),
    sa.Column('material_name', sa.String(length=200), nullable=True),
    sa.Column('supply_quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('arrival_sim_hour', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('target_warehouse_id', sa.String(length=36), nullable=False),
    sa.Column('data_source', sa.String(length=30), nullable=False),
    sa.Column('sync_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['sim_simulation_plan.plan_id'], ),
    sa.ForeignKeyConstraint(['target_warehouse_id'], ['md_warehouse.warehouse_id'], ),
    sa.PrimaryKeyConstraint('supply_id')
    )
    op.create_table('biz_work_order',
    sa.Column('wo_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('wo_no', sa.String(length=50), nullable=False),
    sa.Column('order_no', sa.String(length=50), nullable=True),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=True),
    sa.Column('product_model', sa.String(length=100), nullable=True),
    sa.Column('pcb_layer', sa.Integer(), nullable=True),
    sa.Column('board_size', sa.String(length=50), nullable=True),
    sa.Column('total_comp_qty', sa.Integer(), nullable=True),
    sa.Column('small_comp_qty', sa.Integer(), nullable=True),
    sa.Column('bga_qty', sa.Integer(), nullable=True),
    sa.Column('connector_qty', sa.Integer(), nullable=True),
    sa.Column('panel_qty', sa.Integer(), nullable=True),
    sa.Column('plan_qty', sa.Integer(), nullable=False),
    sa.Column('completed_qty', sa.Integer(), nullable=True),
    sa.Column('qualified_qty', sa.Integer(), nullable=True),
    sa.Column('plan_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('process_route', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=30), nullable=False),
    sa.Column('source_system', sa.String(length=50), nullable=True),
    sa.Column('sync_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['sim_simulation_plan.plan_id'], ),
    sa.PrimaryKeyConstraint('wo_id'),
    sa.UniqueConstraint('plan_id', 'wo_no')
    )
    op.create_table('md_bop',
    sa.Column('bop_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('line_id', sa.String(length=36), nullable=False),
    sa.Column('bop_version', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['md_production_line.line_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['md_product.product_id'], ),
    sa.PrimaryKeyConstraint('bop_id')
    )
    op.create_table('md_operation',
    sa.Column('operation_id', sa.String(length=36), nullable=False),
    sa.Column('line_id', sa.String(length=36), nullable=False),
    sa.Column('operation_code', sa.String(length=50), nullable=False),
    sa.Column('operation_name', sa.String(length=200), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('operation_type', sa.String(length=50), nullable=True),
    sa.Column('is_key_operation', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('creator_binding_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['md_production_line.line_id'], ),
    sa.PrimaryKeyConstraint('operation_id'),
    sa.UniqueConstraint('line_id', 'operation_code')
    )
    op.create_table('res_simulation_result',
    sa.Column('result_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('computation_status', sa.String(length=20), nullable=False),
    sa.Column('computation_start', sa.DateTime(), nullable=True),
    sa.Column('computation_end', sa.DateTime(), nullable=True),
    sa.Column('total_output', sa.Integer(), nullable=True),
    sa.Column('output_per_hour', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('overall_lbr', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('bottleneck_equipment_id', sa.String(length=36), nullable=True),
    sa.Column('bottleneck_utilization', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('material_shortage_count', sa.Integer(), nullable=True),
    sa.Column('material_shortage_minutes', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('equipment_failure_count', sa.Integer(), nullable=True),
    sa.Column('equipment_downtime_minutes', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('result_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['sim_simulation_plan.plan_id'], ),
    sa.PrimaryKeyConstraint('result_id'),
    sa.UniqueConstraint('plan_id')
    )
    op.create_table('sim_anomaly_injection',
    sa.Column('anomaly_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('anomaly_type', sa.String(length=30), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('start_sim_hour', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('duration_minutes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['sim_simulation_plan.plan_id'], ),
    sa.PrimaryKeyConstraint('anomaly_id')
    )
    op.create_table('sim_parameter_override',
    sa.Column('override_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('scope_type', sa.String(length=30), nullable=False),
    sa.Column('scope_id', sa.String(length=36), nullable=True),
    sa.Column('param_key', sa.String(length=50), nullable=False),
    sa.Column('param_value', sa.String(length=200), nullable=False),
    sa.Column('time_range_start', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('time_range_end', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['sim_simulation_plan.plan_id'], ),
    sa.PrimaryKeyConstraint('override_id')
    )
    op.create_table('sim_soft_constraint_config',
    sa.Column('constraint_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('constraint_type', sa.String(length=50), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['sim_simulation_plan.plan_id'], ),
    sa.PrimaryKeyConstraint('constraint_id'),
    sa.UniqueConstraint('plan_id', 'constraint_type')
    )
    op.create_table('tpl_plan_version',
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('version_name', sa.String(length=100), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('is_baseline', sa.Boolean(), nullable=False),
    sa.Column('key_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=False),
    sa.Column('archived_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['sim_simulation_plan.plan_id'], ),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_table('ai_analysis_result',
    sa.Column('ai_result_id', sa.String(length=36), nullable=False),
    sa.Column('result_id', sa.String(length=36), nullable=False),
    sa.Column('bottleneck_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('analysis_summary', sa.Text(), nullable=True),
    sa.Column('knowledge_base_version', sa.String(length=20), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('generation_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['res_simulation_result.result_id'], ),
    sa.PrimaryKeyConstraint('ai_result_id'),
    sa.UniqueConstraint('result_id')
    )
    op.create_table('biz_production_task',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('wo_id', sa.String(length=36), nullable=True),
    sa.Column('stage_id', sa.String(length=36), nullable=False),
    sa.Column('line_id', sa.String(length=36), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('plan_quantity', sa.Integer(), nullable=False),
    sa.Column('completed_qty', sa.Integer(), nullable=True),
    sa.Column('qualified_qty', sa.Integer(), nullable=True),
    sa.Column('production_sequence', sa.Integer(), nullable=False),
    sa.Column('data_source', sa.String(length=30), nullable=False),
    sa.Column('source_system', sa.String(length=50), nullable=True),
    sa.Column('sync_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['md_production_line.line_id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['sim_simulation_plan.plan_id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['md_stage.stage_id'], ),
    sa.ForeignKeyConstraint(['wo_id'], ['biz_work_order.wo_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('md_bop_process',
    sa.Column('bop_process_id', sa.String(length=36), nullable=False),
    sa.Column('bop_id', sa.String(length=36), nullable=False),
    sa.Column('operation_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('standard_ct', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('panel_qty', sa.Integer(), nullable=True),
    sa.Column('ct_per_panel', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('yield_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('standard_worker_count', sa.Integer(), nullable=False),
    sa.Column('min_worker_count', sa.Integer(), nullable=True),
    sa.Column('primary_material_type', sa.String(length=100), nullable=True),
    sa.Column('sop_ref', sa.String(length=500), nullable=True),
    sa.Column('sop_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bop_id'], ['md_bop.bop_id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['md_operation.operation_id'], ),
    sa.PrimaryKeyConstraint('bop_process_id'),
    sa.UniqueConstraint('bop_id', 'sequence')
    )
    op.create_table('md_equipment',
    sa.Column('equipment_id', sa.String(length=36), nullable=False),
    sa.Column('operation_id', sa.String(length=36), nullable=False),
    sa.Column('equipment_code', sa.String(length=50), nullable=False),
    sa.Column('equipment_name', sa.String(length=200), nullable=False),
    sa.Column('equipment_type', sa.String(length=50), nullable=False),
    sa.Column('manufacturer', sa.String(length=200), nullable=True),
    sa.Column('model_no', sa.String(length=100), nullable=True),
    sa.Column('standard_ct', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('creator_binding_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['md_operation.operation_id'], ),
    sa.PrimaryKeyConstraint('equipment_id')
    )
    op.create_table('md_operation_transition',
    sa.Column('transition_id', sa.String(length=36), nullable=False),
    sa.Column('bop_id', sa.String(length=36), nullable=False),
    sa.Column('from_operation_id', sa.String(length=36), nullable=False),
    sa.Column('to_operation_id', sa.String(length=36), nullable=False),
    sa.Column('transfer_time', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('mandatory_wait_time', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('transfer_mode', sa.String(length=30), nullable=True),
    sa.Column('wait_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bop_id'], ['md_bop.bop_id'], ),
    sa.ForeignKeyConstraint(['from_operation_id'], ['md_operation.operation_id'], ),
    sa.ForeignKeyConstraint(['to_operation_id'], ['md_operation.operation_id'], ),
    sa.PrimaryKeyConstraint('transition_id')
    )
    op.create_table('md_staffing_config',
    sa.Column('staffing_id', sa.String(length=36), nullable=False),
    sa.Column('operation_id', sa.String(length=36), nullable=False),
    sa.Column('worker_type_id', sa.String(length=36), nullable=False),
    sa.Column('worker_count', sa.Integer(), nullable=False),
    sa.Column('ct_with_this_count', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('is_standard', sa.Boolean(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['md_operation.operation_id'], ),
    sa.ForeignKeyConstraint(['worker_type_id'], ['md_worker_type.worker_type_id'], ),
    sa.PrimaryKeyConstraint('staffing_id')
    )
    op.create_table('md_wip_buffer',
    sa.Column('wip_id', sa.String(length=36), nullable=False),
    sa.Column('line_id', sa.String(length=36), nullable=False),
    sa.Column('wip_code', sa.String(length=50), nullable=False),
    sa.Column('wip_name', sa.String(length=200), nullable=False),
    sa.Column('capacity_volume', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('capacity_qty', sa.Integer(), nullable=True),
    sa.Column('pre_operation_id', sa.String(length=36), nullable=True),
    sa.Column('post_operation_id', sa.String(length=36), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('creator_binding_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['md_production_line.line_id'], ),
    sa.ForeignKeyConstraint(['post_operation_id'], ['md_operation.operation_id'], ),
    sa.ForeignKeyConstraint(['pre_operation_id'], ['md_operation.operation_id'], ),
    sa.PrimaryKeyConstraint('wip_id')
    )
    op.create_table('res_line_balance_result',
    sa.Column('lb_result_id', sa.String(length=36), nullable=False),
    sa.Column('result_id', sa.String(length=36), nullable=False),
    sa.Column('line_id', sa.String(length=36), nullable=False),
    sa.Column('takt_time', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('lbr', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('balance_loss_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('bottleneck_operation_id', sa.String(length=36), nullable=True),
    sa.Column('bottleneck_ct', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('idle_operation_id', sa.String(length=36), nullable=True),
    sa.Column('operation_load_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('workshop_load_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('factory_load_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['md_production_line.line_id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['res_simulation_result.result_id'], ),
    sa.PrimaryKeyConstraint('lb_result_id')
    )
    op.create_table('res_simulation_state_snapshot',
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('result_id', sa.String(length=36), nullable=False),
    sa.Column('sim_timestamp_sec', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('equipment_states', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('wip_states', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('warehouse_states', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('agv_states', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('snapshot_interval_sec', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['res_simulation_result.result_id'], ),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_table('res_smt_capacity_result',
    sa.Column('smt_result_id', sa.String(length=36), nullable=False),
    sa.Column('result_id', sa.String(length=36), nullable=False),
    sa.Column('time_granularity', sa.String(length=10), nullable=False),
    sa.Column('placement_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('smt_line_count', sa.Integer(), nullable=False),
    sa.Column('total_demand_points', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_effective_capacity_points', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('max_gap_period_label', sa.String(length=20), nullable=True),
    sa.Column('max_gap_lines_needed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['res_simulation_result.result_id'], ),
    sa.PrimaryKeyConstraint('smt_result_id'),
    sa.UniqueConstraint('result_id')
    )
    op.create_table('ai_improvement_suggestion',
    sa.Column('suggestion_id', sa.String(length=36), nullable=False),
    sa.Column('ai_result_id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('suggestion_category', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('expected_impact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('implementation_cost', sa.String(length=20), nullable=True),
    sa.Column('implementation_effort', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_result_id'], ['ai_analysis_result.ai_result_id'], ),
    sa.PrimaryKeyConstraint('suggestion_id')
    )
    op.create_table('biz_wip_buffer_snapshot',
    sa.Column('wip_snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('wip_id', sa.String(length=36), nullable=False),
    sa.Column('material_code', sa.String(length=50), nullable=False),
    sa.Column('current_quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('current_volume', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(), nullable=False),
    sa.Column('data_source', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['sim_simulation_plan.plan_id'], ),
    sa.ForeignKeyConstraint(['wip_id'], ['md_wip_buffer.wip_id'], ),
    sa.PrimaryKeyConstraint('wip_snapshot_id')
    )
    op.create_table('md_bop_process_ng_type',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bop_process_id', sa.String(length=36), nullable=False),
    sa.Column('ng_code', sa.String(length=20), nullable=False),
    sa.Column('occurrence_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bop_process_id'], ['md_bop_process.bop_process_id'], ),
    sa.ForeignKeyConstraint(['ng_code'], ['md_ng_type.ng_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('md_bop_process_param',
    sa.Column('param_id', sa.String(length=36), nullable=False),
    sa.Column('bop_process_id', sa.String(length=36), nullable=False),
    sa.Column('param_name', sa.String(length=200), nullable=False),
    sa.Column('param_value', sa.String(length=200), nullable=True),
    sa.Column('upper_limit', sa.String(length=100), nullable=True),
    sa.Column('lower_limit', sa.String(length=100), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bop_process_id'], ['md_bop_process.bop_process_id'], ),
    sa.PrimaryKeyConstraint('param_id')
    )
    op.create_table('md_equipment_failure_param',
    sa.Column('param_id', sa.String(length=36), nullable=False),
    sa.Column('equipment_id', sa.String(length=36), nullable=False),
    sa.Column('mtbf_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mttr_minutes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('failure_distribution', sa.String(length=20), nullable=True),
    sa.Column('data_source', sa.String(length=100), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['md_equipment.equipment_id'], ),
    sa.PrimaryKeyConstraint('param_id'),
    sa.UniqueConstraint('equipment_id')
    )
    op.create_table('res_smt_capacity_period_result',
    sa.Column('period_result_id', sa.String(length=36), nullable=False),
    sa.Column('smt_result_id', sa.String(length=36), nullable=False),
    sa.Column('period_label', sa.String(length=20), nullable=False),
    sa.Column('period_start_date', sa.Date(), nullable=False),
    sa.Column('period_end_date', sa.Date(), nullable=False),
    sa.Column('working_days', sa.Integer(), nullable=False),
    sa.Column('demand_points', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('theoretical_capacity_points', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('effective_capacity_points', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('gap_points', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('gap_lines_needed', sa.Integer(), nullable=False),
    sa.Column('utilization_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('period_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['smt_result_id'], ['res_smt_capacity_result.smt_result_id'], ),
    sa.PrimaryKeyConstraint('period_result_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('res_smt_capacity_period_result')
    op.drop_table('md_equipment_failure_param')
    op.drop_table('md_bop_process_param')
    op.drop_table('md_bop_process_ng_type')
    op.drop_table('biz_wip_buffer_snapshot')
    op.drop_table('ai_improvement_suggestion')
    op.drop_table('res_smt_capacity_result')
    op.drop_table('res_simulation_state_snapshot')
    op.drop_table('res_line_balance_result')
    op.drop_table('md_wip_buffer')
    op.drop_table('md_staffing_config')
    op.drop_table('md_operation_transition')
    op.drop_table('md_equipment')
    op.drop_table('md_bop_process')
    op.drop_table('biz_production_task')
    op.drop_table('ai_analysis_result')
    op.drop_table('tpl_plan_version')
    op.drop_table('sim_soft_constraint_config')
    op.drop_table('sim_parameter_override')
    op.drop_table('sim_anomaly_injection')
    op.drop_table('res_simulation_result')
    op.drop_table('md_operation')
    op.drop_table('md_bop')
    op.drop_table('biz_work_order')
    op.drop_table('biz_material_supply')
    op.drop_table('biz_inventory_snapshot')
    op.drop_table('biz_demand_forecast')
    op.drop_table('sim_simulation_plan')
    op.drop_table('md_shift')
    op.drop_table('md_production_line')
    op.drop_table('tpl_parameter_template')
    op.drop_table('md_worker_type')
    op.drop_table('md_work_calendar')
    op.drop_table('md_warehouse')
    op.drop_table('md_stage')
    op.drop_table('md_product')
    op.drop_table('md_ng_type')
    op.drop_table('md_material')
    op.drop_table('md_factory')
    # ### end Alembic commands ###
